### ISSUE TITLE
Explorer get back to query result

### ISSUE THREAD

**Issue by srault95** [Widukind/widukind#1]
Issue widukind/widukind-web#26 from @thomasszuber

Hello, 

Thank you for this tool ! However when I search for a series through the explorer and click to vizualize one of the series resulting from the search, I am unable to return to the original search. Rather widukind sends back the original page of the provider without the query terms I entered (in my case IMF) : 

http://widukind.cepremap.org/views/explorer/imf

Thanks in advance

**Comment by thomasbrand** [comment]
Hi @thomasszuber. I think this bug is now fixed in the new version of the website.
