### ISSUE TITLE
Wrong series format - IMF-BOP dataset

### ISSUE THREAD

**Issue by jonasheipertz** [Widukind/widukind#11]
Dear all, 
there seems to be an issue with the OBS_VALUE format in several series of the IMF-BOP dataset. For example:
http://widukind-api.cepremap.org/api/v1/sdmx/IMF/data/BOP/Q.US.IADF-BP6-USD

Numbers of OBS_VALUE contain "-".

Thank you.

Jonas

**Comment by eraviart** [comment]
This issue has been moved to our forum:
https://forum.data.nomics.world/t/wrong-series-format-imf-bop-dataset/25
