### ISSUE TITLE
Sdmx links on IMF datas are not convenient

### ISSUE THREAD

**Issue by srault95** [Widukind/widukind#3]
Issue Widukind/widukind-web#28 from @SuperMayo

Sdmx links for some series have an unusual numerical country code making them unusable for mass downloading.
The country code is not even the ISO numeric code, maybe it's some IMF internal classification.

**Reproduce the bug**:
- Go to the explorer
- Select IMF as provider 
- Select WEO as dataset. _for example_
- Select a subject code :   _GDP per capita in PPP_
- Select 2 series :  _PPPPC.AFG.5_ and _PPPPC.ALB.5_
- Compare the sdmx links. While Afghanistan reads `.../WEO/PPPPC.AFG.512.5` Albania link is `.../WEO/PPPPC.ALB.914.5`.

Is there a way to get rid off this strange numerical code and get something like `.../WEO/PPPPC.AFG.5` ? It's very annoying when you want to download datas for multiple countries.

**Comment by kalessine** [comment]
The IMF has some really strange codes in their SDMX Codelists.. they are specific to the IMF... on their SDMX test page http://sdmxws.imf.org/Gateway/
they list some files for 'Mapping' between IMF country codes and ISO codes

**Comment by eraviart** [comment]
This issue has been moved to our forum:
https://forum.data.nomics.world/t/sdmx-links-on-imf-datas-are-not-convenient/30
