### ISSUE TITLE
[BUG] Missing series when downloading large dataset

### ISSUE THREAD

**Issue by SuperMayo** [Widukind/widukind#5]
When you want to download large dataset, some series are missing without any warning message.

How to reproduce this bug:
- Follow this link (This is the bilateral trade for several countries): http://widukind-api.cepremap.org/api/v1/sdmx/IMF/data/DOT/6.112+156+158+111+132+136+134+193+273+172+228+186+144+196+122+542.A.txg-fob-usd.112+156+158+111+132+136+134+193+273+172+228+186+144+196+122+542
- Search for "273"  ( <kbd> Ctrl </kbd> +<kbd>F</kbd> `"273"`)
- If you look closely you'll see that country `273` (Mexico) is never shown as "reference area", which mean that we don't have exports from Mexico. (searching for `REF-AREA="273"`gives no result)
- If you remove 1 country from the request (for example `542` for Korea) you get the following link: http://widukind-api.cepremap.org/api/v1/sdmx/IMF/data/DOT/6.112+156+158+111+132+136+134+193+273+172+228+186+144+196+122.A.txg-fob-usd.112+156+158+111+132+136+134+193+273+172+228+186+144+196+122
- Now, searching for `REF-AREA="273"` gives you 4 returns (but we should have 14 results as there are 15 countries)

Haven't tried this in JSON, maybe only a SDMX bug.

**Comment by MichelJuillard** [comment]
There is in fact a limit of 1000 series on download, but there is a bug with the missing error message. Given the ease to select data in Widukind, it is best to narrow the search rather than downloading very large data sets.
We are still studying an alternative for downloading large amount of data, if possible using compression.

**Comment by eraviart** [comment]
This issue has been moved to our forum:
https://forum.data.nomics.world/t/missing-series-when-downloading-large-dataset/29/2
