### ISSUE TITLE
startDate in ulstats

### ISSUE THREAD

**Issue by MichelJuillard** [Widukind/widukind#6]
ulstats returns a large integer for startDate that can't be interpreted by Matlab

We need to discuss an alternative specification before implementing it. The problem may also arise for other dates in the JSON

**Comment by mmalter** [comment]
This lack of an epoch() function in Matlab bit me before. It is possible to write one though.

function date = unix2matlab(epoch)
    date = datenum('1970', 'yyyy') + epoch / 864e8;
end

I guess it is safe to assume that any proper language is capable of reading an epoch.

**Comment by mmalter** [comment]
Sorry for being unclear. If this does not work, I would require an example of your input argument.
function date = unix2matlab(epoch)
date = datevec(datenum('1970', 'yyyy') + epoch / 864e5);
end
