### ISSUE TITLE
fetcher INSEE attempts to download non-existing series

### ISSUE THREAD

**Issue by MichelJuillard** [Widukind/widukind#7]
It seems that fetcher INSEE attempts to download non-existing series. For example:

```
CNA-2010-CONSO-MEN-PRODUIT/A88-86
```

A88-66 is not one of the products listed on INSEE web site for this dataset

**Comment by eraviart** [comment]
This issues has been moved to our forum:
https://forum.data.nomics.world/t/insee-fetcher-attempts-to-download-non-existing-series/27
