### ISSUE TITLE
Data Structure has wrong ProviderRef in PayloadStructure

### ISSUE THREAD

**Issue by kalessine** [Widukind/widukind#9]
Hi There!
could you please correct this problem with the SDMX Data Service...
in the data SDMX document, it has a field called 'PayloadStructureType' which contains a reference to the data structure.. (AgencyId/MaintainableId/Version) in this url;
http://widukind-api.cepremap.org/api/v1/sdmx/INSEE/data/IPI-2005-A64/A.CL2.?startPeriod=2000-01-01&endTime=2016-08-01
the payload structure looks like this;
<message:Structure structureID="IPI-2005-A64" dimensionAtObservation="TIME_PERIOD" namespace="urn:sdmx:org.sdmx.infomodel.datastructure.DataStructure=WIDUKIND:IPI-2005-A64(1.0):ObsLevelDim:TIME_PERIOD">common:Structure<URN>urn:sdmx:org.sdmx.infomodel.datastructure.DataStructure=WIDUKIND:IPI-2005-A64(1.0)</URN>/common:Structure

Please note the use of the AgencyID 'WIDUKIND' where the dataflow lists the Structure's AgencyID as 'EUROSTAT'..... so please change this line in the PayloadStructure to the AgencyID of the agency it came from (in this case 'EUROSTAT')
Thanks =D
   JG

**Comment by eraviart** [comment]
This issue has been moved to our forum:
https://forum.data.nomics.world/t/data-structure-has-wrong-providerref-in-payloadstructure/24
